---
- name: Assure requirements are installed
  package:
     name: "{{ item }}"
     state: latest
  with_items:
    - git
    - python-pip
  become: true

- name: Assure python requirements are installed
  pip:
    name: pexpect
    state: latest
  become: true

- name: Clone the repo
  git:
    repo: https://github.com/OpenSprinkler/OpenSprinklerGen2.git
    dest: /usr/local/share/OpenSprinklerGen2
    depth: 1
  become: true

- name: Install OpenSprinkler
  shell: /usr/local/share/OpenSprinklerGen2/build.sh ospi SILENT
  become: true

- name: Check service is running
  service:
   name: OpenSprinkler
   state: started

- name: Check web interface
  uri:
    url: http://localhost:8080
    return_content: yes
  register: check_web

- name: A reminder
  debug:
    msg: "A reminder that the default password for OpenSprinkler is 'opendoor'"
  when: check_web.status == "200"
